import { faker } from '@faker-js/faker';
import fs from 'fs';
import path from 'path';
import type { Model } from '../lib/types';

// This script regenerates the static DEMO_MODELS export in lib/demoData.ts
// (used by `npm run dev` when NEXT_PUBLIC_SANITY_PROJECT_ID=demo-project).
// Running it isn't required, but can help when you want a fresh set of
// random profiles with realistic-looking names and stats.

function getCliArg(name: string) {
  const exact = process.argv.find((arg) => arg.startsWith(`--${name}=`));
  return exact ? exact.slice(name.length + 3) : undefined;
}

const countArg = Number(getCliArg('count') ?? '12');
const seedArg = Number(getCliArg('seed') ?? '20260224');
const MODEL_COUNT = Number.isFinite(countArg) ? Math.max(1, Math.min(200, Math.floor(countArg))) : 12;
const RNG_SEED = Number.isFinite(seedArg) ? Math.floor(seedArg) : 20260224;

faker.seed(RNG_SEED);

const COLORS = [
  { bg: '1a1a1a', fg: 'ffffff' },
  { bg: '2c2c2c', fg: 'e0e0e0' },
  { bg: '0d0d0d', fg: 'cccccc' },
  { bg: '1f1f2e', fg: 'c8c8ff' },
  { bg: '2e1f1f', fg: 'ffc8c8' },
];
function fakeImageTag(text: string, size: { w: number; h: number }) {
  const palette = COLORS[faker.number.int({ min: 0, max: COLORS.length - 1 })] ?? COLORS[0]!;
  return `https://placehold.co/${size.w}x${size.h}/${palette.bg}/${palette.fg}?text=${encodeURIComponent(
    text,
  )}&font=montserrat`;
}
function fakePortfolio(name: string, count: number = 5) {
  return Array.from({ length: count }).map((_, i) => ({
    _type: 'image' as const,
    asset: {
      _ref: `portfolio-${name.toLowerCase().replace(/\s/g, '-')}-${i}`,
      _type: 'reference' as const,
    },
    _demoUrl: fakeImageTag(`${name} #${i + 1}`, { w: 800, h: i % 2 === 0 ? 1200 : 800 }),
  }));
}
function fakePolaroids(name: string, count: number = 3) {
  return Array.from({ length: count }).map((_, i) => ({
    _type: 'image' as const,
    asset: {
      _ref: `polaroid-${name.toLowerCase().replace(/\s/g, '-')}-${i}`,
      _type: 'reference' as const,
    },
    _demoUrl: fakeImageTag(`${name} polaroid ${i + 1}`, { w: 600, h: 600 }),
  }));
}
function randomModel(id: number): Model {
  const gender = faker.helpers.arrayElement(['Male', 'Female', 'Non-Binary'] as const);
  const first = faker.person.firstName(gender === 'Male' ? 'male' : gender === 'Female' ? 'female' : undefined);
  const last = faker.person.lastName();
  const name = `${first} ${last}`;
  const slug = faker.helpers.slugify(name).toLowerCase();
  return {
    _id: `demo-${id}`,
    name,
    slug: { current: slug },
    status: faker.helpers.arrayElement(['Available', 'Travel', 'Unavailable'] as const),
    gender,
    category: faker.helpers.arrayElement(['Mainboard', 'Development', 'Classic'] as const),
    location: `${faker.location.city()}, ${faker.location.country()}`,
    height: faker.number.int({ min: 165, max: 195 }),
    bust: faker.number.int({ min: 75, max: 105 }),
    waist: faker.number.int({ min: 55, max: 85 }),
    hips: faker.number.int({ min: 80, max: 100 }),
    shoe: faker.number.int({ min: 36, max: 45 }),
    hair: faker.lorem.word(),
    eyes: faker.lorem.word(),
    portfolio: fakePortfolio(name, faker.number.int({ min: 3, max: 7 })),
    polaroids: fakePolaroids(name, faker.number.int({ min: 2, max: 5 })),
    coverImage: {
      _type: 'image',
      asset: { _ref: 'placeholder', _type: 'reference' },
    },
  };
}

const models: Model[] = Array.from({ length: MODEL_COUNT }).map((_, i) => randomModel(i));

// write into demoData.ts file
const targetPath = path.join(__dirname, '../lib/demoData.ts');
const content = `import type { Model } from './types';

// this file is autogenerated by scripts/generateDemoData.ts
// run \`npm run generate:demo\` to regenerate

export const DEMO_MODELS: Model[] = ${JSON.stringify(models, null, 2)};
`;
fs.writeFileSync(targetPath, content);
console.log(`Wrote ${models.length} demo models to ${targetPath} (seed=${RNG_SEED})`);
